"""
After the pipeline analysis

merged process from s1.filtering.py, s2a.nt_annotations.py, s3.tables.py

TODO: change into parameters-control script
"""


"""
For a beginner, you should install 
tqdm, pandas and Biopython
All three are popular library and thus you could install them by pip.
Note that the string formator f"" is only implemented in >=3.7 python
"""

from glob import glob
from os.path import *
import os
from tqdm import tqdm
import pandas as pd
from subprocess import check_call
from Bio import SeqIO
import pandas as pd
from os.path import *
import os
from Bio import SeqIO
import copy
from bin.ncbi_convertor import NCBI_convertor
from tqdm import tqdm
from collections import Counter
import sqlite3
from bin.ncbi_convertor import NCBI_convertor
from glob import glob

################   setting 
workdir = '/mnt/ivy/thliao/project/coral_ruegeria/data_otheramplicons/results/amplicon_nirS/20230808/Pdada2_output'
os.chdir(workdir)
query_faa = f"{workdir}/rep.fasta"
bitscore_threshold = 100
raw_ASVtable = f'{workdir}/ASV_table.tsv'
raw_asv = f'{workdir}/rep.fasta'
output_positive_ASV_seq = f'{workdir}/finalized/Positive_rep.fasta'



###! retrieve the information of 656 genomes and the MC informations
used_df = pd.read_excel('/mnt/ivy/thliao/project/coral_ruegeria/info_RuegeriaUsed_20230207.xlsx',index_col=0)
final_genomes = used_df.index[used_df['used in 20220904 OGTree']=='Yes']
pop_file = '/mnt/ivy/thliao/project/coral_ruegeria/data_processing/PopCOGenT/output/coral_20220903_0.000355362.txt.cluster.tab.txt'
pop_df = pd.read_csv(pop_file, sep="\t", index_col=0)
g2pop = pop_df["Main_cluster"].to_dict()
################
# Perform two blastx 
# the query file is the representative sequences generated by the dada2

# one is against SEED sequences of nirS from FunGene (positive search; aim to identify true nirS)
# the other is against swissprot database (negative search; aim to identify and remove non nirS)
################
header = "qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore staxids stitle qframe".split(' ')
check_call(f"blastx -query {query_faa} -db /mnt/ivy/thliao/project/coral_ruegeria/data_otheramplicons/exploring/ecopcr/nirS_protein -num_threads 30 -max_target_seqs 20 -outfmt '6 {' '.join(header)}' -evalue 1e-3 -max_hsps 20 -out ./ASV2funcgene.tsv",shell=1)
check_call(f"blastx -query {query_faa} -db /mnt/home-db/pub/protein_db/swissprot/swissprot -num_threads 30 -max_target_seqs 1000000 -outfmt '6 {' '.join(header)}' -evalue 1e-3 -max_hsps 20 -out ./ASV2swissprot.tsv",shell=1)

###########################
# positive_ofile = f"/mnt/ivy/thliao/project/coral_ruegeria/data_otheramplicons/exploring/nan_nirS/nirS_annotated.txt"
# negative_ofile = f"/mnt/ivy/thliao/project/coral_ruegeria/data_otheramplicons/exploring/nan_nirS/nirS_swissprot_positive_deduplicated.txt"
### parse two tables and concat them together
_d1 = pd.read_csv(f'{workdir}/ASV2funcgene.tsv',sep='\t',index_col=0,header=None)
_d1.columns = header[1:]  # since the first col has been taken as the inedx, so we remove the first one
_d1.loc[:,'type'] = 'SEED'
_d2 = pd.read_csv(f'{workdir}/ASV2swissprot.tsv',sep='\t',index_col=0,header=None)
_d2.columns = header[1:]  
df = pd.concat([_d1,_d2],axis=0)
df.loc[:,'name'] = df.index
df = df.loc[(df['bitscore']>bitscore_threshold),:]
sorted_df = df.sort_values('bitscore',ascending=False)

#########  !!!!!! Filtering (db based) !!!!!!  
all_ASV = list(set(sorted_df.index))
top10_df = sorted_df.groupby('name').head(10)
asv2nirS = set()
for asv,idx in tqdm(top10_df.groupby('name').groups.items()):
    ssubdf = top10_df.loc[idx[0],:]
    if len(ssubdf.shape)==1:
        ssubdf = top10_df.loc[[idx[0]],:]
    xs = [1 if sid =='SEED' else 0 for sid in ssubdf['type']]
    if sum(xs[:10])>=5:
        # if over 50% of them are close to the SEED nirS, it is a true nirS
        asv2nirS.add(asv)
###########################
######### retrieve all true nirS and filter out nirS with length not in 220-240
seqs = list(SeqIO.parse(query_faa,'fasta'))
nirS_seqs = [_ for _ in seqs if _.id in asv2nirS]
length_seqs = [_ for _ in nirS_seqs if len(str(_.seq))>=220 and len(str(_.seq))<=240]
print(len(seqs),len(nirS_seqs),len(length_seqs))
# 13014 9564 9551
# 38597 27096 27044  # 
######## output
with open(output_positive_ASV_seq,'w') as f1:
    SeqIO.write(length_seqs,f1,'fasta-2line')
    

############################################################## step2
genomes = [_.split('/')[-1].replace(".faa",'') 
           for _ in glob("/mnt/ivy/thliao/project/coral_ruegeria/data_processing/all_faa/*.faa")]
from ete3 import Tree
genomes = Tree('/mnt/ivy/thliao/project/coral_ruegeria/ipynb/paper_denitrification/used_Speciestree.newick',3).get_leaf_names()

asv_tab = pd.read_csv(raw_ASVtable,sep='\t')
seq2asv = {v:k for k,v in asv_tab['Sequence'].to_dict().items()}
seq2sid = {str(r.seq):r.id for r in SeqIO.parse(raw_asv,'fasta')}
mapping = {sid:seq2asv[seq] for seq,sid in seq2sid.items()}
positive_fa = {_.id:_ for _ in SeqIO.parse(output_positive_ASV_seq,'fasta')}
subasv = asv_tab.loc[[mapping[_] for _ in positive_fa],:].iloc[:,:-1]

######### generating the ASV table and renamed ASV of true nirS
positive_fa = {_.id:_ for _ in SeqIO.parse(output_positive_ASV_seq,'fasta')}
subasv = asv_tab.loc[[mapping[_] for _ in positive_fa],:].iloc[:,:-1]
idmapping = {}
with open('./finalized/positive_ASV.fa','w') as f1:
    records = list(positive_fa.values())
    for r in records:
        oid = r.id
        r.id = 'ASV' + '{n:06}'.format(n=int(mapping[r.id].replace('preASV','')))
        idmapping[oid] = r.id
    SeqIO.write(records,f1,'fasta-2line')
subasv.index = ['ASV' + '{n:06}'.format(n=int(_.replace('preASV',''))) for _ in subasv.index]
subasv.to_csv('./finalized/positive_ASV_table.tsv',sep='\t',index=1)
with open('./finalized/ASV.IDmapping','w') as f1:
    for k,v in idmapping.items():
        f1.write(f"{k}\t{v}\n")
########################################################
### blastn against nt database
########################################################
rep_otu = output_positive_ASV_seq
db = '/mnt/ivy/thliao/db/tmp_nt/20230817/nt'
# db = '/home-db/pub/nucl_db/nt/20210102/blast_db/nt'
cmd = f"blastn -query {rep_otu} -db {db} -num_threads 30 -max_target_seqs 1000000 -outfmt '6 qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore ssciname staxids stitle' -evalue 1e-10 -max_hsps 1 -out {dirname(rep_otu)}/Positive2nt_blastn.tbl " 
########################################################
### blastn against nt database
########################################################
luolab_nirS = '/mnt/ivy/thliao/project/coral_ruegeria/data_otheramplicons/refgenes/K15864'
cmd = f"blastx -query {rep_otu} -db {luolab_nirS} -num_threads 30 -max_target_seqs 20 -outfmt '6 qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore staxids stitle qframe' -evalue 1e-3 -max_hsps 20 -out {dirname(rep_otu)}/positive_656G.tbl " 
os.system(cmd)
########################################################
### parse two blast results and 
########################################################
sdf = pd.read_csv(f'{dirname(rep_otu)}/../Positive2nt_blastn.tbl',header=None,sep='\t',index_col=0,low_memory=False)
sdf.columns=f"saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore ssciname staxids stitle".split(' ')
sdf2 = pd.read_csv(f'{dirname(rep_otu)}/../positive_656G.tbl',header=None,sep='\t',index_col=0)
sdf2.columns=f"saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore staxids stitle qframe".split(' ')
sdf = pd.concat([sdf,sdf2],axis=0).sort_values('bitscore',ascending=False)
sdf.loc[:,'name'] = sdf.index
sdf = sdf.loc[sdf['bitscore']>100,:]

all_sids = list(set(sdf['saccver']))
all_sids = [_ for _ in all_sids if _.split('_')[0] not in genomes]
print(len(set(all_sids)))

########################################################
### retrieve the taxon id from SQL database
########################################################
n = ', '.join([f"'{_}'" for _ in  all_sids])
conn = sqlite3.connect('/home-db/pub/nucl_db/nt/20210102/nucl2taxid/n2tid.db')
cur = conn.cursor()
cur.execute(f"SELECT * FROM nucl2tid INDEXED BY nuclID_index WHERE nuclID in ({n}) ")
results = cur.fetchall()
conn.close()
print(len(results),len(all_sids))
id2tid = dict(results)


########################################################
####### convert the taxon id of the hit nucceotide into species name
########################################################
convertor = NCBI_convertor([],"nuccore")
id2taxon = convertor.get_taxons_from_tid(tids=id2tid)
tax_df = pd.DataFrame.from_dict(id2taxon, orient='index')
tax_tab = "/home-user/thliao/.cache/ncbi-genome-download/taxonomy.tab"
db_tax_df = pd.read_csv(tax_tab, sep="\t", index_col=0)
db_tax_df.index = [_.replace('GCA_','GNM').replace('GCF_','GNM') for _ in db_tax_df.index]
db_tax_df = db_tax_df.loc[[_.split('_')[0] for _ in list(set(sdf2['saccver'])) if _.split('_')[0] in db_tax_df.index],:]
_t2t = {_.split('_')[0]:_ for _ in list(set(sdf2['saccver'])) if _.split('_')[0] in db_tax_df.index}
db_tax_df.index = [_t2t[_] for _ in db_tax_df.index]
for r,row in db_tax_df.iterrows():
    tax_df.loc[r,:] = row.reindex(tax_df.columns)
for _ in list(sdf2['saccver']):
    if _ not in tax_df.index:
        tax_df.loc[_,:] = tax_df.loc['CP000032.1',:]
        tax_df.loc[_,'species'] = 'Luolab Ruegeria (656G)'
missing_ids = set(sdf['saccver'].unique()).difference(tax_df.index)
for _ in ['CP020560.1', 'CP027169.1', 'CP029093.1']:
    tax_df.loc[_,:] = tax_df.loc['AE004091.2',:]
### here is manually added
for mid in missing_ids:
    tax_df.loc[mid,:] = tax_df.loc['AP012280.1',:] 
if not exists(join(dirname(rep_otu),'nt_qaccver_taxinfo.tsv')):    
    tax_df.to_csv(join(dirname(rep_otu),'nt_qaccver_taxinfo.tsv'),sep='\t',index=1)
else:
    tax_df = pd.read_csv(join(dirname(rep_otu),'../nt_qaccver_taxinfo.tsv'),sep='\t',index_col=0)

###############################################################
######## remove uncultured first 
###############################################################
uncultured = tax_df.loc[tax_df['species'].str.contains('uncultured')]
other_df = tax_df.loc[tax_df.index.difference(uncultured.index),:]
unknown_asv = []
for asv,g in tqdm(sdf.groupby('name')):
    subg = g.loc[~g['saccver'].isin(uncultured.index)]
    if  subg.shape[0] ==0:
        unknown_asv.append('uncultured')
removed_sdf = sdf.loc[~sdf['saccver'].isin(uncultured.index),:]
removed_uncultured = sdf.loc[~sdf['name'].isin(unknown_asv),:]
print(len(set(sdf.index)),len(set(removed_uncultured.index)))
# 9550 9550

###############################################################
######## select top10
###############################################################
t10_sdf = removed_sdf.groupby('name').head(10)
t10_sdf.loc[:,'OTU'] = t10_sdf.index

unknown_ids=[]
xs = []
for otu,row in tqdm(t10_sdf.iterrows(),total=t10_sdf.shape[0]):
    sid = row['saccver'].strip()
    if sid in uncultured.index:
        xs.append('uncultured') 
    elif sid in other_df.index:
        xs.append(str(other_df.loc[sid,'family']))
    elif sid.split('_')[0] in genomes:
        xs.append('Luolab Ruegeria')
    else:
        unknown_ids.append(sid)
        xs.append('uncultured') 
t10_sdf.loc[:,'subject tax'] = xs
classified_nirS_otu = list(set(t10_sdf.index))
t10_sdf.to_csv(join(dirname(rep_otu),'t10_nt.tsv'),sep='\t')
###############################################################
########! assign taxonomy information to each ASV
###############################################################
levels = ['superkingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species']
from collections import Counter
asv2tax = {}
final_types = {}
for otu in tqdm(classified_nirS_otu):
    tax_l = [_ for _ in t10_sdf.loc[otu,'subject tax'] if _!='uncultured']
    sub_t10_sdf = t10_sdf.loc[otu,:]
    if len(sub_t10_sdf.shape)==1:
        sub_t10_sdf = t10_sdf.loc[[otu],:]
    sub_t10_sdf = sub_t10_sdf.loc[sub_t10_sdf['subject tax']!='nan',:]
    if sub_t10_sdf.shape[0]==0:continue
    x = sub_t10_sdf.iloc[0,0]
    row = tax_df.loc[x,:]
    
    last_one = ''
    final_n = []
    for l in levels:
        v = str(row.to_dict().get(l,''))
        if not v or v in ['NA','nan']:
            v = 'Unclassified ' + last_one.replace('Unclassified ','')
        else:
            v = v
        last_one = l
        final_n.append(v)
    asv2tax[otu] = ';'.join(final_n)

###############################################################
########! transform the asv2tax and the ASV table into a taxonomic abundance table 
###############################################################
id2asv = dict([r.split('\t') for r in open('./finalized/ASV.IDmapping').read().strip().split('\n')])
asv2tax = {id2asv[k]:v for k,v in asv2tax.items()}
rawotu_df = pd.read_csv('./finalized/positive_ASV_table.tsv',sep='\t',index_col=0)
asv2reads = rawotu_df['sum'].to_dict()
unknown = ';'.join(['Unclassified Bacteria']*len(levels))
ofile = './finalized/nirS_nt_TAX.txt'
with open(ofile,'w') as f1:
    f1.write('Sequence.ID\ttax_blastp_fungene_550_without_uncultured\tsum_reads\n')
    for asv in sorted(rawotu_df.index):
        tax = asv2tax.get(asv,unknown)
        f1.write(f"{asv}\t{tax}\t{asv2reads[asv]}\n")

rawotu_df.loc[:,'genus'] = [asv2tax.get(asv,unknown).split(';')[-2] for asv in rawotu_df.index]
genus2reads = rawotu_df.groupby('genus').sum()['sum']
genus2ratio = rawotu_df.groupby('genus').sum()['sum']/rawotu_df['sum'].sum()*100
ofile = './finalized/stat_nirS_nt_genus.txt'
with open(ofile,'w') as f1:
    f1.write('Genus\tBlastP_FunGeneExcludingUncultured_reads\tproportion_reads\n')
    for genus,ratio in sorted(genus2ratio.items(),key=lambda x:x[1],reverse=True):
        f1.write(f"{genus}\t{genus2reads[genus]}\t{ratio}\n")   
        
rawotu_df.loc[:,'family'] = [asv2tax.get(asv,unknown).split(';')[-3] for asv in rawotu_df.index]
family2reads = rawotu_df.groupby('family').sum()['sum']
family2ratio = rawotu_df.groupby('family').sum()['sum']/rawotu_df['sum'].sum()*100
ofile = './finalized/stat_nirS_nt_family.txt'
with open(ofile,'w') as f1:
    f1.write('Family\tBlastP_FunGeneExcludingUncultured_reads\tproportion_reads\n')
    for family,ratio in sorted(family2ratio.items(),key=lambda x:x[1],reverse=True):
        f1.write(f"{family}\t{family2reads[family]}\t{ratio}\n")   
        